### ISSUE TITLE
How do I change the loading bar color?

### ISSUE THREAD

**Issue by josheewa** [jcgter777/CubeTimerICE#10]
@SanjivanM Can you change the color to blue? And fix the text in Loading? (Maybe smaller text)

**Comment by SanjivanM** [comment]
change the det(2 before the For( loop, change the det(74 ... I'll fix them.

**Comment by SanjivanM** [comment]
as for the text size, it's that way so the rubik's cube sprite will fit, It's just there ro make things look cooler :P

**Comment by josheewa** [comment]
Oh. The loading thing is a rubik's cube spr? :P 
 Can it not overlap anything? @SanjivanM
